/**
 * Overlap detection (`projectplan.md` §6.2).
 *
 * The intersection is ten lines. The **classification** is the product.
 *
 * §6.2 draws three outcomes and they call for three different actions from
 * Claude, which is the only reason the distinction is worth computing:
 *
 * - **disjoint** — merge in any order; the gate is a formality.
 * - **shared file** — merge sequentially and let the test gate find out. Two
 *   workers editing different regions of one file usually merges cleanly; two
 *   editing the same region does not, and that is what the gate is for.
 * - **shared integration file** — `package.json`, a lockfile, a barrel, a router
 *   index. These are the ones where git merges *successfully* and produces
 *   something wrong: two workers each adding a dependency to `package.json`
 *   merge to a file with both, and a lockfile that agrees with neither. §6.2's
 *   advice is to warn up front, and better still to give one worker ownership of
 *   the integration points — which is planning advice, so this module's job is
 *   to make the situation visible early enough for Claude to act on it.
 *
 * **Why a set intersection is a valid overlap test at all:** `createWorktree`
 * resolves the base ref to a sha and branches every worker from that same sha
 * (see `worktree.ts`). If the bases could differ, two workers "changing the same
 * file" might be changing two different files that happen to share a path, and
 * comparing name sets would mean nothing. {@link detectOverlap} checks the bases
 * agree and says so when they do not, rather than quietly producing an answer
 * that is only true by luck.
 *
 * Pure over its inputs: no git, no filesystem. The caller supplies changed-file
 * sets (from `changedFiles`) and this decides what they mean.
 */

import { basename } from "node:path";

// ---------------------------------------------------------------------------
// What counts as an integration file
// ---------------------------------------------------------------------------

/**
 * Exact basenames whose merge is almost always semantically wrong even when it
 * is textually clean: manifests, lockfiles and the toolchain's own config.
 *
 * A lockfile deserves special mention. Two workers that each ran an install
 * produce two lockfiles derived from different manifests; git will merge them
 * line-wise into a third that was never generated by any resolver. That file
 * looks fine and installs the wrong tree.
 */
const INTEGRATION_BASENAMES: ReadonlySet<string> = new Set([
  "package.json",
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  "bun.lock",
  "bun.lockb",
  "deno.json",
  "deno.lock",
  "tsconfig.json",
  "jsconfig.json",
  "Cargo.toml",
  "Cargo.lock",
  "go.mod",
  "go.sum",
  "requirements.txt",
  "pyproject.toml",
  "poetry.lock",
  "uv.lock",
  "Pipfile",
  "Pipfile.lock",
  "Gemfile",
  "Gemfile.lock",
  "composer.json",
  "composer.lock",
  "pom.xml",
  "build.gradle",
  "build.gradle.kts",
  "Makefile",
  "Dockerfile",
  "docker-compose.yml",
  "docker-compose.yaml",
]);

/**
 * Barrels and re-export hubs: the file every feature has to edit one line of.
 *
 * `index.ts` is the canonical case. Two workers adding an export each will merge
 * clean if the lines are apart and conflict if they are adjacent, and neither
 * outcome is one Claude should discover from a test failure.
 */
const BARREL_BASENAMES: ReadonlySet<string> = new Set([
  "index.ts",
  "index.js",
  "index.tsx",
  "index.jsx",
  "index.mjs",
  "index.cjs",
  "mod.ts",
  "mod.rs",
  "lib.rs",
  "__init__.py",
  "barrel.ts",
]);

/** Router tables and app-wiring: same hazard, less regular naming. */
const WIRING_PATTERN = /(^|[/._-])(routes?|router|routing|registry|manifest|schema|migrations?)([/._-]|\.[a-z]+$|$)/i;

/**
 * Prose is never an integration point.
 *
 * Without this, `docs/routing-notes.md` matches the wiring pattern and Claude is
 * warned that two workers editing a document might produce a lockfile nobody
 * generated. The warning is advisory, so a false positive is cheap — but a
 * warning that fires on documentation is a warning that gets ignored on
 * `package.json`.
 */
const PROSE = /\.(md|mdx|markdown|txt|rst|adoc)$/i;

/**
 * Is this a file whose clean merge is not evidence of a correct merge?
 *
 * Deliberately a name-shaped heuristic rather than content analysis. It is
 * advisory — the output warns Claude, it never blocks a merge — so a false
 * positive costs one sentence of caution and a false negative costs a test-gate
 * round trip. Both are cheap; parsing every manifest format is not.
 */
export function isIntegrationFile(path: string): boolean {
  const name = basename(path);
  if (INTEGRATION_BASENAMES.has(name)) return true;
  if (PROSE.test(name)) return false;
  if (BARREL_BASENAMES.has(name)) return true;
  return WIRING_PATTERN.test(path);
}

// ---------------------------------------------------------------------------
// Shapes
// ---------------------------------------------------------------------------

/** One worker's contribution to the comparison. */
export interface OverlapInput {
  readonly workerID: string;
  /** Repo-relative paths, as `changedFiles` returns them. */
  readonly files: readonly string[];
  /** The sha this worker branched from. Compared, not trusted. */
  readonly baseSha?: string;
}

/** How bad the worst overlap is. Ordered: each is strictly worse than the last. */
export type OverlapClass = "disjoint" | "shared_file" | "shared_integration_file";

export interface SharedFile {
  readonly path: string;
  /** Every worker that touched it, sorted. Always length ≥ 2. */
  readonly workers: readonly string[];
  readonly integration: boolean;
}

export interface OverlapPair {
  readonly a: string;
  readonly b: string;
  readonly files: readonly string[];
}

export interface OverlapReport {
  /** The worst class present. `disjoint` when nothing is shared. */
  readonly classification: OverlapClass;
  readonly workers: readonly string[];
  /** Every path more than one worker changed, sorted by path. */
  readonly shared: readonly SharedFile[];
  /** The shared paths that are integration points — a subset of `shared`. */
  readonly integrationFiles: readonly string[];
  /** Which pairs collide, for a caller that wants to order or split a wave. */
  readonly pairs: readonly OverlapPair[];
  /**
   * Set when the inputs do not all share a base sha.
   *
   * Not an error, because a caller may legitimately compare workers from two
   * runs — but the intersection below is only meaningful for a common base, so
   * saying so beats returning a confident wrong answer.
   */
  readonly baseMismatch?: { readonly bases: readonly string[] };
}

// ---------------------------------------------------------------------------

/**
 * Intersect the changed-file sets and classify the result (§6.2).
 *
 * Workers contributing no files are kept in `workers` and simply never appear in
 * an intersection: "this worker changed nothing" is a fact worth carrying to the
 * merge, which has to report it rather than treat it as an error (a `completed`
 * worker may genuinely have produced no commit — see `merge.ts`).
 */
export function detectOverlap(inputs: readonly OverlapInput[]): OverlapReport {
  const workers = inputs.map((i) => i.workerID).sort();

  /** path → the workers that touched it. A `Map` of `Set`s, so duplicate paths
   * within one worker's list cannot inflate the count to a false overlap. */
  const owners = new Map<string, Set<string>>();
  for (const input of inputs) {
    for (const file of input.files) {
      const at = owners.get(file) ?? new Set<string>();
      at.add(input.workerID);
      owners.set(file, at);
    }
  }

  const shared: SharedFile[] = [];
  for (const [path, who] of [...owners.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    if (who.size < 2) continue;
    shared.push({ path, workers: [...who].sort(), integration: isIntegrationFile(path) });
  }

  const integrationFiles = shared.filter((s) => s.integration).map((s) => s.path);
  const classification: OverlapClass =
    integrationFiles.length > 0 ? "shared_integration_file" : shared.length > 0 ? "shared_file" : "disjoint";

  const bases = [...new Set(inputs.map((i) => i.baseSha).filter((s): s is string => typeof s === "string" && s !== ""))];

  return {
    classification,
    workers,
    shared,
    integrationFiles,
    pairs: pairsOf(shared),
    ...(bases.length > 1 ? { baseMismatch: { bases: bases.sort() } } : {}),
  };
}

/** Every colliding pair, with the files they collide on. */
function pairsOf(shared: readonly SharedFile[]): OverlapPair[] {
  const byPair = new Map<string, { a: string; b: string; files: string[] }>();
  for (const file of shared) {
    for (let i = 0; i < file.workers.length; i++) {
      for (let j = i + 1; j < file.workers.length; j++) {
        const a = file.workers[i]!;
        const b = file.workers[j]!;
        const key = `${a} ${b}`;
        const entry = byPair.get(key) ?? { a, b, files: [] };
        entry.files.push(file.path);
        byPair.set(key, entry);
      }
    }
  }
  return [...byPair.values()].sort((x, y) => x.a.localeCompare(y.a) || x.b.localeCompare(y.b));
}

/**
 * A merge order that puts the least entangled workers first.
 *
 * Not clever, and not trying to be: §6.3 merges sequentially and the gate is the
 * safety net, so all this buys is that when a wave *does* go red, the rollback
 * costs less work — the workers that collide with nothing are already in. Ties
 * break on id so the order is deterministic, which matters more than optimality
 * for a pipeline whose failures have to be reproducible.
 */
export function suggestMergeOrder(report: OverlapReport): string[] {
  const weight = new Map<string, number>(report.workers.map((w) => [w, 0]));
  for (const file of report.shared) {
    for (const w of file.workers) {
      weight.set(w, (weight.get(w) ?? 0) + (file.integration ? 2 : 1));
    }
  }
  return [...report.workers].sort((a, b) => (weight.get(a) ?? 0) - (weight.get(b) ?? 0) || a.localeCompare(b));
}
